# Generated by Django 5.1.3 on 2024-11-17 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_delievered',
            new_name='order_delivered',
        ),
        migrations.CreateModel(
            name='OrdersUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.order')),
                ('username', models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_id', 'username'), name='unique_user_order')],
            },
        ),
    ]
