# Generated by Django 5.1.3 on 2024-11-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_order_delievered_order_order_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_delivered',
            new_name='order_delievered',
        ),
    ]
