# Generated by Django 5.1.3 on 2024-11-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_order_delivered_order_order_delievered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_id', models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.order')),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(through='login.ProductOrders', to='login.product'),
        ),
    ]
