# Generated by Django 5.1.3 on 2024-11-20 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_delievered',
        ),
        migrations.AddField(
            model_name='productorders',
            name='product_delivered',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='productorders',
            name='product_order',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
