# Generated by Django 5.1.3 on 2024-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorders',
            old_name='product_order',
            new_name='product_ordered',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product_img/'),
        ),
    ]
