# Generated by Django 5.1.3 on 2024-11-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_product_order_productorders_product_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='product_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
